### ISSUE TITLE
release: java_tools_javac11-v9.1 release and java_tools_javac14-v1.1 release

### ISSUE THREAD

**Issue by andrefmrocha** [bazelbuild/java_tools#29]
With [this PR](https://github.com/bazelbuild/bazel/pull/11766), there is a goal to output compilation diagnostics through the BEP. Due to this, changes were introduced to the java_tools, namely to the `BazelJavaBuilder`. For this, it is then required to release a new version of the java_tools.

Please correct me if the versioning system is not as follows. 

The changes to the builder were introduced in [b9a591e25d4325ae274661d69bd2fff46713e616](https://github.com/bazelbuild/bazel/pull/11766/commits/b9a591e25d4325ae274661d69bd2fff46713e616).

**Comment by philwo** [comment]
@andrefmrocha It seems like the tests for the PR don't pass currently - is that because it introduces the changes to BazelJavaBuilder, but then also already uses them? We can only build java_tools releases from commits that are already in Bazel's master branch, otherwise we risk not being able to later determine from which source code the release was actually built.

Could you split the PR into two parts, one with just the additional (but not yet used) features for BazelJavaBuilder - then we can get that submitted, do a java_tools release, then the second part of your PR that enables and actually uses the feature can pass the tests and we can merge that, too?

**Comment by andrefmrocha** [comment]
@philwo yes that was the case! I've just created a PR for that [here](https://github.com/bazelbuild/bazel/pull/11908)
